shared:
    environment:
        NODE_ENV: production
jobs:
    main:
        image: node:10
        requires: [~commit, ~pr]
        steps:
            - init: npm install
            - test: npm test
    build-node8:
        image: node:8
        steps: 
            - echo: echo test
        requires: [main]
        
    # B and C will run in parallel
    build-node10:
        image: node:8
        steps:
            - publish: |
                npm run publish
        requires: [main]
    delploy:  
        image: ubuntu
        steps:
            - verify: echo verify
        requires: [build-node10, build-node8]
