jobs:
    main:
        image: node:10
        requires: [~commit, ~pr]
        steps:
            - init: npm install
            - test: npm test
    build-node8:
        image: node:8
        steps: 
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 8"
        requires: [main]
        
    # B and C will run in parallel
    build-node10:
        image: node:8
        steps:
            - init: npm install
            - test: npm test
            - publish: |
                echo "publishing against node 10"
        requires: [main]
    delploy:  
        image: ubuntu
        steps:
            - verify: echo verify
        requires: [build-node10, build-node8]
